apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: lancr
build:
  artifacts:
    - image: piotrostr/lancr
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/sa.yaml
    - k8s/secrets.yaml
    - k8s/typesense.yaml
    - k8s/auth_service.yaml
    - k8s/gateway.yaml
    - k8s/ingress.yaml
    - k8s/server.yaml
    # - k8s/website.yaml
    - k8s/helloworld.yaml
