apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: lancr
build:
  artifacts:
    - image: gcr.io/asoltd-guilds/lancr
  googleCloudBuild:
    dockerImage: gcr.io/cloud-builders/docker
    projectId: asoltd-guilds
manifests:
  rawYaml:
    - k8s/manifest.yaml
deploy:
  kubectl:
    defaultNamespace: default