/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum v1RoleCategory {
    ROLE_CATEGORY_UNSPECIFIED = 'ROLE_CATEGORY_UNSPECIFIED',
    ROLE_CATEGORY_DESIGNER = 'ROLE_CATEGORY_DESIGNER',
    ROLE_CATEGORY_PRODUCT_DESIGNER = 'ROLE_CATEGORY_PRODUCT_DESIGNER',
    ROLE_CATEGORY_SOFTWARE_DEVELOPMENT = 'ROLE_CATEGORY_SOFTWARE_DEVELOPMENT',
    ROLE_CATEGORY_PRESENTOR = 'ROLE_CATEGORY_PRESENTOR',
    ROLE_CATEGORY_MANAGER = 'ROLE_CATEGORY_MANAGER',
    ROLE_CATEGORY_ENGINEER = 'ROLE_CATEGORY_ENGINEER',
}
