name: Build

on: [pull_request]

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.3"

      - name: Build
        run: |
          chmod +x ./hack/build.sh
          ./hack/build.sh
