name: Coverage

on: [push, pull_request]

jobs:
  test:
    name: Run Tests with Coverage
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: "auth"
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.5.0
        with:
          workload_identity_provider: "projects/asoltd-guilds/locations/global/workloadIdentityPools/gh-actions-pool/providers/gh-actions-provider"
          service_account: "firestore-editor@asoltd-guilds.iam.gserviceaccount.com"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.3"

      - name: Run coverage
        run: |
          chmod +x ./hack/coverage.sh
          ./hack/coverage.sh
