name: Push Images

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # TODO this might require Cloud Build permissions, but think that the
      # Cloud Deployer sa has it by default
      - id: "auth"
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.5.0
        with:
          workload_identity_provider: "projects/808202803134/locations/global/workloadIdentityPools/gh-actions-pool/providers/gh-actions-provider"
          service_account: "cloud-deployer-sa@asoltd-guilds.iam.gserviceaccount.com"

      - name: Run skaffold build
        uses: hiberbee/github-action-skaffold@1.19.0
        with:
          command: build
