name: Test

on: [push]

jobs:
  test:
    name: Run Custom Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: latest  # Use the latest version of Go

    - name: Run tests
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        chmod 600 $GOOGLE_APPLICATION_CREDENTIALS
        chmod +x ./hack/test.sh
        ./hack/test.sh
